version: "3.5"

services:
  test:
    build: .
    command: pytest
    volumes:
      - .:/code
  web:
    build: .
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: python manage.py loaddata usagetypes.json
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
